// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class CuttingRoomFloor
    {
        public static class Cell
        {
            private static FormLink<ICellGetter> Construct(uint id) => new FormLink<ICellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ICellGetter> CRFFrostRiverRogensHouse => Construct(0x1a8b79);
            public static FormLink<ICellGetter> CRFHeljarchenBlacksmith => Construct(0x2ec5d);
            public static FormLink<ICellGetter> CRFFrostRiverMeadery => Construct(0x31377);
            public static FormLink<ICellGetter> CRFFrostRiverHenrikHouse => Construct(0x1a8b7a);
            public static FormLink<ICellGetter> CRFHeljarchenApothecary => Construct(0x2ec5e);
            public static FormLink<ICellGetter> CRFWhiterunWintersandManorHouse => Construct(0x1a42b);
            public static FormLink<ICellGetter> CRFWhiterunMaidenLoomManor => Construct(0x21c2b);
            public static FormLink<ICellGetter> CRFHeljarchenJensHouse => Construct(0x2ec5f);
            public static FormLink<ICellGetter> CRFHeljarchenHeigensHouse => Construct(0x2ec60);
            public static FormLink<ICellGetter> CRFStonehillsArgiFarseersHouse => Construct(0x14249);
            public static FormLink<ICellGetter> CRFStonehillsGesturHouse => Construct(0xdef99);
            public static FormLink<ICellGetter> CRFBarleydarkFarmInterior => Construct(0x1317e);
            public static FormLink<ICellGetter> CRFStonehillsAleucHouse => Construct(0x30fda);
            public static FormLink<ICellGetter> CRFStonehillsTalibHouse => Construct(0xcef99);
            public static FormLink<ICellGetter> CRFIrontreeMillTrilfsHouse => Construct(0x259f3);
        }
    }
}
