// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class ELE_SSE
    {
        public static class ImageSpace
        {
            private static FormLink<IImageSpaceGetter> Construct(uint id) => new FormLink<IImageSpaceGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IImageSpaceGetter> _1ELE_Dungeon_IS => Construct(0x7216);
            public static FormLink<IImageSpaceGetter> _1ELE_Interior_IS => Construct(0x7217);
            public static FormLink<IImageSpaceGetter> _1ELE_Test_IS => Construct(0x60ba7);
        }
    }
}
