// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class ELE_SSE
    {
        public static class LightingTemplate
        {
            private static FormLink<ILightingTemplateGetter> Construct(uint id) => new FormLink<ILightingTemplateGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILightingTemplateGetter> _1ELE_Bright_Ice_LT => Construct(0xa389);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_Ice_LT => Construct(0xa38b);
            public static FormLink<ILightingTemplateGetter> _1ELE_Medium_Ice_LT => Construct(0xa38a);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_Falmer_FogDark_LT => Construct(0xa68f);
            public static FormLink<ILightingTemplateGetter> _1ELE_Medium_ThinFog_LT => Construct(0x25cb2);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_ThinFog_LT => Construct(0x1ee72);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_Falmer_FogFar_LT => Construct(0x1e4bf);
            public static FormLink<ILightingTemplateGetter> _1ELE_Medium_Falmer_LT => Construct(0xdfe4);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_Falmer_LT => Construct(0xdfe3);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_Dwemer_LT => Construct(0xdfe2);
            public static FormLink<ILightingTemplateGetter> _1ELE_Brighter_Ice_LT => Construct(0xcfbb);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_Falmer_FogNear_LT => Construct(0xc32f);
            public static FormLink<ILightingTemplateGetter> _1ELE_Medium_LT => Construct(0x7071);
            public static FormLink<ILightingTemplateGetter> _1ELE_Bright_LT => Construct(0x98a3);
            public static FormLink<ILightingTemplateGetter> _1ELE_Dark_LT => Construct(0x7072);
            public static FormLink<ILightingTemplateGetter> _1ELE_Test_LT => Construct(0x60ba8);
            public static FormLink<ILightingTemplateGetter> _1ELE_Brighter_LT => Construct(0x9e16);
        }
    }
}
