// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class ELE_SSE
    {
        public readonly static ModKey ModKey = ModKey.FromNameAndExtension("ELE_SSE.esp");
    }
}
