// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class Ravengate
    {
        public static class Cell
        {
            private static FormLink<ICellGetter> Construct(uint id) => new FormLink<ICellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ICellGetter> RVHCellManor => Construct(0xaa33);
            public static FormLink<ICellGetter> RVHCellRatwayDepths => Construct(0xaf14c);
            public static FormLink<ICellGetter> RVHCellOblivion => Construct(0x10563f);
            public static FormLink<ICellGetter> RVHCellRatway => Construct(0x447c6);
        }
    }
}
