// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class Ravengate
    {
        public static class Light
        {
            private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILightGetter> RVH_Light_DefaultCandleLight01NS_Loraliah => Construct(0x77472);
            public static FormLink<ILightGetter> RVH_Light_NPC_Loraliah_Balefire_Projectile => Construct(0xfb3e9);
            public static FormLink<ILightGetter> RVH_Light_NPC_Loraliah_Balefire_Hand => Construct(0xfb3e8);
            public static FormLink<ILightGetter> RVH_Light_LightCampFire01_Arena => Construct(0xa9fb5);
            public static FormLink<ILightGetter> RVH_Light_NPC_Flamia_Hellstorm_Projectile => Construct(0xe1e70);
            public static FormLink<ILightGetter> RVH_Light_NPC_Flamia_Hellstorm_Cast => Construct(0xe1e6f);
            public static FormLink<ILightGetter> RVH_Light_Oblivion_Fire => Construct(0x105687);
            public static FormLink<ILightGetter> RVH_Light_Oblivion_Shock => Construct(0x105689);
            public static FormLink<ILightGetter> RVH_Light_DefaultCandleLight01NS_Saturated_Hemi => Construct(0x17f081);
            public static FormLink<ILightGetter> RVH_Light_Ambient_Xivaz => Construct(0x1bb9d);
            public static FormLink<ILightGetter> RVH_Light_Bounce_Point => Construct(0x53bfa);
            public static FormLink<ILightGetter> RVH_Light_NPC_CauldronBornLich_CorruptionBolt_Cast => Construct(0x1e47bf);
            public static FormLink<ILightGetter> RVH_Light_NPC_Xivaz_Torment_Cast => Construct(0x12dee3);
            public static FormLink<ILightGetter> RVH_Light_NPC_Flamia_DefenseMatrix_Hands => Construct(0xe6fcf);
            public static FormLink<ILightGetter> RVH_Light_NPC_Flamia_Feedback_Cast => Construct(0xe1e79);
            public static FormLink<ILightGetter> RVH_Light_DefaultCandleLight01NS_Saturated => Construct(0x62fb1);
            public static FormLink<ILightGetter> RVH_Light_Ambient_Bright => Construct(0x1bb9b);
            public static FormLink<ILightGetter> RVH_Light_NPC_Loraliah_PrismaticBolt_Hand => Construct(0x16fcdd);
            public static FormLink<ILightGetter> RVH_Light_NPC_Loraliah_PrismaticBolt_Projectile => Construct(0x16fcde);
            public static FormLink<ILightGetter> RVH_Light_Bounce_Poison => Construct(0x20cdb);
            public static FormLink<ILightGetter> RVH_Light_SurfaceOfTheSun => Construct(0x12df00);
            public static FormLink<ILightGetter> RVH_Light_NPC_Xivaz_Torment_Projectile => Construct(0x12dee4);
            public static FormLink<ILightGetter> RVH_Light_Oblivion_Frost => Construct(0x10568b);
            public static FormLink<ILightGetter> RVH_Light_DeathFire => Construct(0x3f674);
            public static FormLink<ILightGetter> RVH_Light_DefaultCandleLight01NSDesat_Bright => Construct(0x77459);
            public static FormLink<ILightGetter> RVH_Light_IceTorch01_Fast_KingCereus => Construct(0x7c581);
            public static FormLink<ILightGetter> RVH_Light_NPC_Loraliah_Apocalypse_Projectile => Construct(0x16fccc);
            public static FormLink<ILightGetter> RVH_Light_NPC_Loraliah_Apocalypse_Hand => Construct(0x16fccb);
            public static FormLink<ILightGetter> RVH_Light_NPC_Xivaz_Implosion_Cast => Construct(0x12def4);
            public static FormLink<ILightGetter> RVH_Light_LightCampFire01_Shadows => Construct(0x53c0d);
            public static FormLink<ILightGetter> RVH_Light_NPC_Flamia_Feedback_Projectile => Construct(0xe1e7a);
            public static FormLink<ILightGetter> RVH_Light_DefaultCandleLight01NS_Bright => Construct(0x7745a);
            public static FormLink<ILightGetter> RVH_Light_BurnItDown => Construct(0x1bbec4);
            public static FormLink<ILightGetter> RVH_Light_DefaultTorch01NS_Bright => Construct(0x7746d);
            public static FormLink<ILightGetter> RVH_Light_ZanathProjector => Construct(0xa9fb2);
            public static FormLink<ILightGetter> RVH_Light_Bounce_Weak => Construct(0x53bde);
            public static FormLink<ILightGetter> RVH_Light_Bounce_Default => Construct(0x20ce0);
            public static FormLink<ILightGetter> RVH_Light_NPC_Flamia_DisruptionBolt_Projectile => Construct(0xe1e91);
            public static FormLink<ILightGetter> RVH_Light_NPC_Flamia_DisruptionBolt_Cast => Construct(0xe1e90);
            public static FormLink<ILightGetter> RVH_Light_Ambient => Construct(0x1bb99);
            public static FormLink<ILightGetter> RVH_Light_RedLanterns_Redoran => Construct(0x353bf);
            public static FormLink<ILightGetter> RVH_Light_RedCandles => Construct(0x353bb);
        }
    }
}
