// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class BSHeartland
    {
        public static class Light
        {
            private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILightGetter> CYRCandleOrangeTint => Construct(0xd79a8);
            public static FormLink<ILightGetter> Alikr_OrangeFlicker_NEW_CYR => Construct(0xb0ce6);
            public static FormLink<ILightGetter> CYRCandleOrangeTintNS => Construct(0xb0b64);
            public static FormLink<ILightGetter> CYRKvatchIntroScene01FakeLight => Construct(0xaebcd);
            public static FormLink<ILightGetter> CYRDefaultTorch01NSDesat_MoveLess => Construct(0xf7f13);
            public static FormLink<ILightGetter> CYRBrumaFightersGuildLight01 => Construct(0x1092);
            public static FormLink<ILightGetter> CYRLightForgeFire01Interior => Construct(0x1113);
            public static FormLink<ILightGetter> CYRCathedralSunlight01 => Construct(0x1301);
            public static FormLink<ILightGetter> CYRCathedralCandleLight01NS => Construct(0x1304);
            public static FormLink<ILightGetter> CYRCathedralCandleLight01 => Construct(0x1305);
            public static FormLink<ILightGetter> CYRCathedralSunlight01NS => Construct(0x137c);
            public static FormLink<ILightGetter> CYRLightCampFireShadow => Construct(0x3681);
            public static FormLink<ILightGetter> CYRLightCandleStreet01Shadow => Construct(0x3ab0);
            public static FormLink<ILightGetter> CYRBrumaLightFireNS => Construct(0x3b94);
            public static FormLink<ILightGetter> CYRLightCampFireNS => Construct(0x3b96);
            public static FormLink<ILightGetter> CYRBrumaLightFireShadow => Construct(0x3bfb);
            public static FormLink<ILightGetter> CYRLightCandleStreet01NS => Construct(0x2da15);
            public static FormLink<ILightGetter> CYRWispStalkMushroomLight => Construct(0x5b871);
            public static FormLink<ILightGetter> CYRLightCandleAleswell01NS => Construct(0x648bf);
            public static FormLink<ILightGetter> CYRLightCandleAleswell02NS => Construct(0x64927);
            public static FormLink<ILightGetter> CYRMagicLightLightSpellOrange => Construct(0x6b57d);
            public static FormLink<ILightGetter> CYRMagicLightLightSpellHand01Orange => Construct(0x6b57e);
            public static FormLink<ILightGetter> CYRMagicLightFrostFireball01 => Construct(0x7231f);
            public static FormLink<ILightGetter> CYRdunBeastsMawLightCampFireShadow => Construct(0x73a64);
            public static FormLink<ILightGetter> CYRdunBeastsMawxCaveSunlightSpot => Construct(0x73a67);
            public static FormLink<ILightGetter> CYRAyleidBlueLight => Construct(0x740ec);
            public static FormLink<ILightGetter> CYRToadstoolSunlight01 => Construct(0x7972e);
            public static FormLink<ILightGetter> CYRSilverToothOrangeSpot => Construct(0x79f18);
            public static FormLink<ILightGetter> CYRGuttedMineOrangeSpot => Construct(0x7c92f);
            public static FormLink<ILightGetter> CYRFalmerPurple01NS_Sideways => Construct(0x7c930);
            public static FormLink<ILightGetter> CYRSidewaysCaveBlueBounce => Construct(0x7c931);
            public static FormLink<ILightGetter> CYRAyleidGreenLight => Construct(0x80f76);
            public static FormLink<ILightGetter> CYRAyleidWhiteLight => Construct(0x80f77);
            public static FormLink<ILightGetter> CYRAyleidWhiteLightShadow02 => Construct(0x80f78);
            public static FormLink<ILightGetter> CYRAyleidWhiteLightShadow01 => Construct(0x83f23);
            public static FormLink<ILightGetter> CYRAyleidWhiteBounce01NS => Construct(0x83f38);
            public static FormLink<ILightGetter> CYRLightAyleidMagic => Construct(0x8421b);
            public static FormLink<ILightGetter> CYRMagicAyleidLightBeamHand01 => Construct(0x86809);
            public static FormLink<ILightGetter> CYRdunBlueFireLightShad => Construct(0x87691);
            public static FormLink<ILightGetter> CYRdunBlueCandleLight01NS => Construct(0x87696);
            public static FormLink<ILightGetter> CYRdunBlueCandleLight01 => Construct(0x876d3);
            public static FormLink<ILightGetter> CYRAyleidBlueLightShadow => Construct(0x892d0);
            public static FormLink<ILightGetter> CYRAyleidWhitePulsatingLight => Construct(0x892d4);
            public static FormLink<ILightGetter> CYRAyleidGreenLightShadow => Construct(0x89dcd);
            public static FormLink<ILightGetter> CYRAyleidYellowLight => Construct(0x89f4f);
            public static FormLink<ILightGetter> CYRFXAyleidCrystalYellowOLD => Construct(0x89f50);
            public static FormLink<ILightGetter> CYRFXAyleidCrystalGreen => Construct(0x89f51);
            public static FormLink<ILightGetter> CYRAyleidBlueLight_Desat => Construct(0x8bcd1);
            public static FormLink<ILightGetter> CYRAyleidBlueLightShadow_Desat => Construct(0x8bcd2);
            public static FormLink<ILightGetter> CYRSunlight75 => Construct(0xb4404);
            public static FormLink<ILightGetter> CYRdunBlueFireLight => Construct(0xb4d7e);
            public static FormLink<ILightGetter> CYRFXAyleidCrystalYellow => Construct(0xb4dfb);
            public static FormLink<ILightGetter> CYRFXAyleidCrystalBlue => Construct(0xb4e74);
            public static FormLink<ILightGetter> CYRAyleidBlueLightShad_Desat => Construct(0xb4e79);
            public static FormLink<ILightGetter> CYRAyleidYellowLightShadow => Construct(0xb4ffa);
            public static FormLink<ILightGetter> CYRFXAyleidCrystalRed => Construct(0xcb8c8);
            public static FormLink<ILightGetter> CYRAyleidRedLight => Construct(0xcb8ca);
            public static FormLink<ILightGetter> CYRAyleidWellLight => Construct(0xd6a38);
        }
    }
}
