// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class LegacyoftheDragonborn
    {
        public static class Cell
        {
            private static FormLink<ICellGetter> Construct(uint id) => new FormLink<ICellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ICellGetter> DBMDGArmory => Construct(0x168884);
            public static FormLink<ICellGetter> DBMJolgeirrBarrow => Construct(0x11cbaa);
            public static FormLink<ICellGetter> DBMDGNaturalScienceHaunted => Construct(0x17cbfe);
            public static FormLink<ICellGetter> DBMQA2 => Construct(0x18f66e);
            public static FormLink<ICellGetter> DBMDGSafehouse => Construct(0xaeace);
            public static FormLink<ICellGetter> DBMRkund01 => Construct(0x504bbe);
            public static FormLink<ICellGetter> DBMFortPalePass => Construct(0x128f86);
            public static FormLink<ICellGetter> DBMTrinimacTemple02 => Construct(0x26ffad);
            public static FormLink<ICellGetter> DBMDGPlanetarium => Construct(0x18f863);
            public static FormLink<ICellGetter> DBMDGHallofHeroesHeist => Construct(0x2ae7d5);
            public static FormLink<ICellGetter> DBMDGArmoryWest => Construct(0x2b487a);
            public static FormLink<ICellGetter> SancreTorMainHall => Construct(0x121bac);
            public static FormLink<ICellGetter> DBMDGHallofHeroes => Construct(0x125ee6);
            public static FormLink<ICellGetter> DBMJournalDungeon01 => Construct(0x1d5b20);
            public static FormLink<ICellGetter> DBMFieldStation03 => Construct(0x2f4a2e);
            public static FormLink<ICellGetter> SancreTorPrisons => Construct(0x122369);
            public static FormLink<ICellGetter> DBMDGEastExhibitHalls => Construct(0x125c71);
            public static FormLink<ICellGetter> DBMRkund03 => Construct(0x50a049);
            public static FormLink<ICellGetter> DBMFortPalePassStoreroom => Construct(0x1b3cb);
            public static FormLink<ICellGetter> DBMAyleidPocketRealm => Construct(0x166d76);
            public static FormLink<ICellGetter> DBMRkund02 => Construct(0x505676);
            public static FormLink<ICellGetter> DBMGreenwallRuins => Construct(0x23cbd8);
            public static FormLink<ICellGetter> DBMRkund06 => Construct(0x50fe28);
            public static FormLink<ICellGetter> DBMDGNaturalScience => Construct(0x1256c8);
            public static FormLink<ICellGetter> DBMAirshipCabin => Construct(0x37bf27);
            public static FormLink<ICellGetter> SancreTorTiberSeptimShrine => Construct(0x122da7);
            public static FormLink<ICellGetter> DBMPalePassPassage => Construct(0x2055d);
            public static FormLink<ICellGetter> DBMRkund05 => Construct(0x50fe29);
            public static FormLink<ICellGetter> SancreTorSealedHalls => Construct(0x122587);
            public static FormLink<ICellGetter> DBMRainsShelter => Construct(0x64f7d);
            public static FormLink<ICellGetter> SancreTorCatacombs => Construct(0x1226bd);
            public static FormLink<ICellGetter> DBMQA => Construct(0x1252e1);
            public static FormLink<ICellGetter> DBMDragonsFall => Construct(0x1265ab);
            public static FormLink<ICellGetter> DBMTrinimacTemple01 => Construct(0x25b8ef);
            public static FormLink<ICellGetter> DBMMAASEAftlandAnnex => Construct(0x5c7ee3);
            public static FormLink<ICellGetter> DBMGuildhouse => Construct(0x62832);
            public static FormLink<ICellGetter> DBMDregasVolarInt => Construct(0x125a26);
            public static FormLink<ICellGetter> DBMRkund04 => Construct(0x50f330);
            public static FormLink<ICellGetter> DBMWindcallerPassN => Construct(0x1942fa);
            public static FormLink<ICellGetter> DBMSanctum => Construct(0x14dd0);
            public static FormLink<ICellGetter> DBMDGHallofSecretsBare => Construct(0xa9278);
            public static FormLink<ICellGetter> DBMEngelmannsSanctuary => Construct(0x1938dc);
            public static FormLink<ICellGetter> SancreTorHallOfJudgement => Construct(0x1226be);
            public static FormLink<ICellGetter> DBMFieldStation01 => Construct(0x1d5a02);
            public static FormLink<ICellGetter> DBMDGLibrary => Construct(0x2f8d08);
            public static FormLink<ICellGetter> DBMMAASEXribAnnex => Construct(0x5c7ee4);
            public static FormLink<ICellGetter> DBMSagruunde => Construct(0x27f80f);
            public static FormLink<ICellGetter> DBMDGArmoryEast => Construct(0x167b25);
            public static FormLink<ICellGetter> DLC2MoesringPass02DBM => Construct(0x5a9779);
            public static FormLink<ICellGetter> DBMDragonsFallDepths => Construct(0x1266b1);
            public static FormLink<ICellGetter> DBMRavenRest => Construct(0x120ee1);
            public static FormLink<ICellGetter> DBMWindcallerPassS => Construct(0x1943cd);
            public static FormLink<ICellGetter> DBMDGHallofHeroesHaunted => Construct(0x1abb45);
            public static FormLink<ICellGetter> DBMMAASEIrkDescent => Construct(0x5c7ee5);
            public static FormLink<ICellGetter> DBMEngelmannsRest => Construct(0x1938c0);
            public static FormLink<ICellGetter> DBMSnowElfTemple => Construct(0x22c23c);
            public static FormLink<ICellGetter> DBMDragonsFallSanctum => Construct(0x127b84);
            public static FormLink<ICellGetter> DBMFieldStation02 => Construct(0x28ee1e);
            public static FormLink<ICellGetter> DBMMAASEIrkRefuge => Construct(0x5c7ee6);
            public static FormLink<ICellGetter> DBMFortPalePassVaults => Construct(0x1a5e9);
            public static FormLink<ICellGetter> DBMDGStoreroom => Construct(0x12517d);
            public static FormLink<ICellGetter> DBMDGDragonbornHall => Construct(0x741acf);
            public static FormLink<ICellGetter> DBMFortPalePassWestTower => Construct(0x1af0d);
            public static FormLink<ICellGetter> DBMDebugRoom => Construct(0x6a9a13);
            public static FormLink<ICellGetter> DBMDeepholme => Construct(0x5955);
            public static FormLink<ICellGetter> DBMDGHallofSecrets => Construct(0x18f4fb);
            public static FormLink<ICellGetter> _0SancreTorSacrarium => Construct(0x121748);
            public static FormLink<ICellGetter> _0SancreTorEstTower => Construct(0x121761);
            public static FormLink<ICellGetter> _0SancreTorWestTower => Construct(0x12176b);
            public static FormLink<ICellGetter> _0SancreTorEntry => Construct(0x121757);
            public static FormLink<ICellGetter> _0SancreTorGate => Construct(0x121755);
            public static FormLink<ICellGetter> PaleGate => Construct(0x128884);
            public static FormLink<ICellGetter> PalePassFortress => Construct(0x1289e3);
            public static FormLink<ICellGetter> PalePassShip => Construct(0x1289e5);
            public static FormLink<ICellGetter> PassToCirodiil => Construct(0x128d96);
            public static FormLink<ICellGetter> Wilderness01 => Construct(0x128d94);
            public static FormLink<ICellGetter> WindPassStart => Construct(0x19431f);
            public static FormLink<ICellGetter> WindPassCenter => Construct(0x19432f);
            public static FormLink<ICellGetter> ClearingCamp => Construct(0x194329);
            public static FormLink<ICellGetter> WindPassEnd => Construct(0x19432b);
        }
    }
}
