// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class LegacyoftheDragonborn
    {
        public static class ImageSpace
        {
            private static FormLink<IImageSpaceGetter> Construct(uint id) => new FormLink<IImageSpaceGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IImageSpaceGetter> dunEngelmannRest_ImageSpace => Construct(0x33d893);
            public static FormLink<IImageSpaceGetter> DBM_HauntedMuseumIMG => Construct(0x539193);
        }
    }
}
