// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class LegacyoftheDragonborn
    {
        public static class Light
        {
            private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILightGetter> DBM_ringlight => Construct(0x1264dd);
            public static FormLink<ILightGetter> WWWSolitudeInnFirePlacesShadowDefault => Construct(0x12895d);
            public static FormLink<ILightGetter> FXLightWhiteBasicDBM => Construct(0x13d901);
            public static FormLink<ILightGetter> DBM_BluePulseLight => Construct(0x16644a);
            public static FormLink<ILightGetter> DBM_MAASE_LightBlue => Construct(0x236cac);
            public static FormLink<ILightGetter> DBM_MAASE_LightGreen => Construct(0x236cad);
            public static FormLink<ILightGetter> DBM_MAASE_LightRed => Construct(0x236cae);
            public static FormLink<ILightGetter> DBM_TorchREPLICA => Construct(0x2a7687);
            public static FormLink<ILightGetter> DBMhandofglorylight01 => Construct(0x42e8c3);
            public static FormLink<ILightGetter> FalmerBlueLight01NSDBM => Construct(0x4fa8fb);
            public static FormLink<ILightGetter> DBM_AzuraBlue01Pulse => Construct(0x50fe36);
            public static FormLink<ILightGetter> dbm_moonlightSpot => Construct(0x539195);
            public static FormLink<ILightGetter> DBM_Torch => Construct(0x7666f4);
            public static FormLink<ILightGetter> DwarvenHemi_Spot => Construct(0x5bf18);
            public static FormLink<ILightGetter> DBMFXLightGreenBlueGlow => Construct(0xb4122);
            public static FormLink<ILightGetter> DBM_Moonlight => Construct(0xca1a3);
            public static FormLink<ILightGetter> HHLight01WWW => Construct(0x122368);
            public static FormLink<ILightGetter> DBMGoldlight => Construct(0x125585);
            public static FormLink<ILightGetter> DBM_goldflicker => Construct(0x125e6d);
            public static FormLink<ILightGetter> DBM_daedriclight => Construct(0x1264c7);
        }
    }
}
