// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class LanternsOfSkyrim
    {
        public readonly static ModKey ModKey = ModKey.FromNameAndExtension("Lanterns Of Skyrim - All In One - Main.esm");
    }
}
