// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class Darkend
    {
        public static class Cell
        {
            private static FormLink<ICellGetter> Construct(uint id) => new FormLink<ICellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ICellGetter> XJKphalosPortWarehouse => Construct(0x829a6);
            public static FormLink<ICellGetter> XJKSwampCatacombs => Construct(0x48ff81);
            public static FormLink<ICellGetter> XJKcastleInteriorGROUNDfloor => Construct(0xa60f5);
            public static FormLink<ICellGetter> XJKcastleInteriorLIBRARYfloor => Construct(0x284e9a);
            public static FormLink<ICellGetter> XJKAncientTowerDeepDeeps => Construct(0xc281f);
            public static FormLink<ICellGetter> XJKAncientTowerDeeps03 => Construct(0x1b6d43);
            public static FormLink<ICellGetter> XJKAbandonedMansionInterior => Construct(0x387357);
            public static FormLink<ICellGetter> XJKphalosCurch => Construct(0x21f10);
            public static FormLink<ICellGetter> XJKMine => Construct(0x3fdfb2);
            public static FormLink<ICellGetter> XJKAncientTowerDeeps => Construct(0xb59ae);
            public static FormLink<ICellGetter> XJKcastleInteriorFIRSTfloor => Construct(0x27f6cc);
            public static FormLink<ICellGetter> XJKphalosChurchCatacombs => Construct(0x2c385);
            public static FormLink<ICellGetter> XJKFortSmallinterior => Construct(0x504e7);
            public static FormLink<ICellGetter> XJKcastleInteriorSECONDfloor => Construct(0x28246d);
            public static FormLink<ICellGetter> XJKAncientTowerDeepDeepsLAVA => Construct(0x21bfbf);
            public static FormLink<ICellGetter> XJKFarmInteriors => Construct(0x502a5);
            public static FormLink<ICellGetter> XJKphalosShipsInteriors => Construct(0x367c9);
            public static FormLink<ICellGetter> XJKfortress => Construct(0x2c5b7);
            public static FormLink<ICellGetter> XJKcastleBasement => Construct(0x27ca16);
            public static FormLink<ICellGetter> XJKcastleInteriorTOWERstairs => Construct(0x2f3ec2);
            public static FormLink<ICellGetter> FortressCastle00 => Construct(0xff7fb);
            public static FormLink<ICellGetter> FortressCastle01 => Construct(0x10217c);
            public static FormLink<ICellGetter> FortressCastle02 => Construct(0x1df8ea);
            public static FormLink<ICellGetter> FortressCastle03 => Construct(0x265464);
            public static FormLink<ICellGetter> PlainsBonefire => Construct(0xd71);
            public static FormLink<ICellGetter> OgresCaveEntrance => Construct(0x10216c);
            public static FormLink<ICellGetter> Port => Construct(0xd69);
            public static FormLink<ICellGetter> ChurchEntrance => Construct(0xd73);
            public static FormLink<ICellGetter> AncientShrine => Construct(0xdb5);
            public static FormLink<ICellGetter> FortressGate => Construct(0xff7cb);
            public static FormLink<ICellGetter> FortressBridge => Construct(0xff7fd);
            public static FormLink<ICellGetter> FortressPlainsGate => Construct(0xd7b);
            public static FormLink<ICellGetter> DarkendfortressBeachEntrance => Construct(0xd81);
            public static FormLink<ICellGetter> Oldgraveyard => Construct(0xd8d);
            public static FormLink<ICellGetter> Fortcliff => Construct(0xd97);
            public static FormLink<ICellGetter> Refuge => Construct(0xda3);
            public static FormLink<ICellGetter> EastRoad => Construct(0xda5);
            public static FormLink<ICellGetter> OldGraveyardNew => Construct(0xdcd);
            public static FormLink<ICellGetter> FishermensCamp => Construct(0xff7b5);
            public static FormLink<ICellGetter> PortalStart => Construct(0xd7f);
            public static FormLink<ICellGetter> PortalMountain => Construct(0xd85);
            public static FormLink<ICellGetter> FrozenGroundsBatlleAftermath => Construct(0xd87);
            public static FormLink<ICellGetter> GoldOre => Construct(0xd93);
            public static FormLink<ICellGetter> ThePit => Construct(0xd99);
            public static FormLink<ICellGetter> Snowbegining => Construct(0xd9d);
            public static FormLink<ICellGetter> AncientBridge => Construct(0xdb9);
            public static FormLink<ICellGetter> SECathedral => Construct(0xdbd);
            public static FormLink<ICellGetter> DarkendTowerExterior => Construct(0xdf3);
            public static FormLink<ICellGetter> AncientTowerEntrance => Construct(0xf70b);
            public static FormLink<ICellGetter> DarkendOpenInteriorOutsideFront => Construct(0xf844);
            public static FormLink<ICellGetter> DarkendOpenInteriorCenter => Construct(0xf897);
            public static FormLink<ICellGetter> DarkendOpenInteriorCOCmarker => Construct(0xf8ce);
            public static FormLink<ICellGetter> DarkendOpenInteriorOutsideBack => Construct(0xf910);
            public static FormLink<ICellGetter> Wildernesss => Construct(0x422b86);
            public static FormLink<ICellGetter> Swamp2 => Construct(0x41d5b0);
            public static FormLink<ICellGetter> Swamp1 => Construct(0x41d5b2);
            public static FormLink<ICellGetter> Bonfire => Construct(0x41d5c2);
            public static FormLink<ICellGetter> GuardiansRestLowerEntrance => Construct(0x41d5c4);
            public static FormLink<ICellGetter> aaaPortalStart => Construct(0x41d5ce);
            public static FormLink<ICellGetter> Start => Construct(0x41d57e);
            public static FormLink<ICellGetter> Pond => Construct(0x41d5d2);
            public static FormLink<ICellGetter> GuardiansRest => Construct(0x41d5d4);
            public static FormLink<ICellGetter> BonfireNew => Construct(0x41d5e4);
            public static FormLink<ICellGetter> GuardiansRestUpperEntrance => Construct(0x41d5e6);
            public static FormLink<ICellGetter> HighTerrace => Construct(0x41d5f6);
        }
    }
}
