// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class Darkend
    {
        public static class Light
        {
            private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILightGetter> XJKTorch01Shadow256 => Construct(0x3b62e7);
            public static FormLink<ILightGetter> XJKAlikr_OrangeFlickerShadRED => Construct(0x394ef);
            public static FormLink<ILightGetter> XJKFXRedBossFountainLightSHADOW => Construct(0x202b81);
            public static FormLink<ILightGetter> XJKAlikr_OrangeFlickerShadREDnoShadow => Construct(0xbfefb);
            public static FormLink<ILightGetter> XJKMagicLightAbsorbGreenProjectile => Construct(0x3b62c3);
            public static FormLink<ILightGetter> XJKFXRedBossFountainLight => Construct(0x7b0d1);
            public static FormLink<ILightGetter> XJKIceCavern_Sunlight2SHADOW => Construct(0x202bab);
            public static FormLink<ILightGetter> XJKIceCavern_Sunlight2 => Construct(0xb85a9);
            public static FormLink<ILightGetter> XJKAlikr_OrangeFlickerREDShadowSPOT => Construct(0x202b86);
            public static FormLink<ILightGetter> XJKIceCavern_Sunlight2LAVA => Construct(0x20544f);
            public static FormLink<ILightGetter> XJKIceCavern_Sunlight2LAVAshadow => Construct(0x2055a4);
            public static FormLink<ILightGetter> XJKIceCavern_Sunlight2ShadowOmni => Construct(0x49acfb);
            public static FormLink<ILightGetter> XJKFXRedLampLight => Construct(0x27738d);
        }
    }
}
