// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class HelgenReborn
    {
        public static class Cell
        {
            private static FormLink<ICellGetter> Construct(uint id) => new FormLink<ICellGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ICellGetter> aaaBalokHouse04 => Construct(0x31f4c);
            public static FormLink<ICellGetter> aaaBalokTowerDisplay => Construct(0x4a592);
            public static FormLink<ICellGetter> aaaBalokTowerLower => Construct(0x28dac);
            public static FormLink<ICellGetter> aaaBalokHouse05 => Construct(0x31eac);
            public static FormLink<ICellGetter> aaaBalokHouseHill03 => Construct(0x7fd96);
            public static FormLink<ICellGetter> aaaBalokDraugrCrypt02 => Construct(0x13df76);
            public static FormLink<ICellGetter> aaaBalokHouse01 => Construct(0x320dd);
            public static FormLink<ICellGetter> aaaBalokBanditCrypt01 => Construct(0xf5015);
            public static FormLink<ICellGetter> aaaBalokThalmorPrison02 => Construct(0x128d7);
            public static FormLink<ICellGetter> aaaBalokHelgenInn => Construct(0x31d3b);
            public static FormLink<ICellGetter> aaaBalokHamingsHouse => Construct(0x1226d7);
            public static FormLink<ICellGetter> aaaBalokVampLair => Construct(0xf8e6e);
            public static FormLink<ICellGetter> aaaBalokFightCave => Construct(0x62838);
            public static FormLink<ICellGetter> aaaBalokTower => Construct(0x28d9a);
            public static FormLink<ICellGetter> aaaBalokHouseHill04 => Construct(0x7fe11);
            public static FormLink<ICellGetter> aaaBalokThalmorPrison => Construct(0x11c3c);
            public static FormLink<ICellGetter> aaaBalokHouseHill01 => Construct(0x7f1d8);
            public static FormLink<ICellGetter> aaaBalokDraugrCrypt => Construct(0x1102fa);
            public static FormLink<ICellGetter> aaaBalokOrphansCave => Construct(0x8cec9);
            public static FormLink<ICellGetter> aaaBalokDummyCell => Construct(0x25ba7);
            public static FormLink<ICellGetter> aaaBalokBrothel => Construct(0x31731);
            public static FormLink<ICellGetter> aaaBalokAerandilShip => Construct(0x93869);
            public static FormLink<ICellGetter> aaaBalokNecroLair => Construct(0xf88fa);
            public static FormLink<ICellGetter> aaaBalokHouseHill05 => Construct(0x7fe8c);
            public static FormLink<ICellGetter> aaaWereBanditMine01 => Construct(0xd62);
            public static FormLink<ICellGetter> aaaBalokReinhardtInterior => Construct(0x60154);
            public static FormLink<ICellGetter> aaaBalokDoorRoom => Construct(0x850c6);
            public static FormLink<ICellGetter> aaaBalokHouseHill02 => Construct(0x7fd1b);
            public static FormLink<ICellGetter> aaaBalokHouse03 => Construct(0x31f41);
            public static FormLink<ICellGetter> aaaBalokCrypt01 => Construct(0x59299);
            public static FormLink<ICellGetter> aaaBalokMine01 => Construct(0x103a23);
            public static FormLink<ICellGetter> aaaBalokBanditMine => Construct(0x11610f);
            public static FormLink<ICellGetter> aaaBalokHouse02 => Construct(0x32059);
            public static FormLink<ICellGetter> Origin => Construct(0x1102fd);
            public static FormLink<ICellGetter> Finale => Construct(0x110304);
            public static FormLink<ICellGetter> Exit => Construct(0x110307);
            public static FormLink<ICellGetter> Temple => Construct(0x110328);
            public static FormLink<ICellGetter> Entrance => Construct(0x1102f5);
        }
    }
}
