// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class HelgenReborn
    {
        public static class Light
        {
            private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ILightGetter> Balok_Light_MnDremoraPurple => Construct(0x10bcab);
            public static FormLink<ILightGetter> Balok_Light_MnDremoraGhostly => Construct(0x10b73e);
            public static FormLink<ILightGetter> Balok_Light_MnDremoraGhostlyNS => Construct(0x10d7cb);
            public static FormLink<ILightGetter> BalokBrazierLightsCavern => Construct(0x59ef6);
        }
    }
}
